#!/bin/bash

if [ $# -eq 0 ] 
  then
    echo "ERROR: No arguments supplied"
    exit 1

for i in $@ ; do 
  if ! [[ "$i" =~ ^-?[0-9]+$ ]] ; then
    echo "Invalid input: Enter file name"
    exit 1
  fi
done

java -cp hw3.jar:classes main.Main $1