#!/bin/bash

if [ $# -eq 0 ] 
  then
    echo "ERROR: No files supplied"
    exit 1
elif [ $# -ge 2 ] 
  then
    echo "ERROR: Too many arguments supplied"
    exit 1
fi

FILE=$1
if [ -f "$FILE" ]; then
    echo "$FILE exists"
    java -cp hw3.jar:classes Main.Main $1
else 
    echo "$FILE does not exist"
fi
